### ISSUE TITLE
Is there a version of this running online?

### ISSUE THREAD

**Issue by ianengelbrecht** [maxxxxxdlp/phylogenetic_tree#2]
Hi guys, are you hosting an instance of this online at present? If so please add the URL to the readme. Otherwise I take this is has to be installed and run locally?

**Comment by maxpatiiuk** [comment]
Hi, this was hosted online but is not available at the moment as we are in the middle of transitioning to new servers.

You can install this locally. The documentation is still up to date. If you have any questions feel free to post them here.

The tool supports `Worms`, `GBIF`, `ITIS` and `Catalog Of Life` data sources (there is a separate branch for each).

For all sources except for `Worms`, the tool would download the newest data from the aggregator automatically.

There is a docker composition that allows to host the tool for multiple data sources at once - https://github.com/specify/taxa_tree_docker
